### ISSUE TITLE
The schema of the request does not support specific Joi.object methods

### ISSUE THREAD

**Issue by nataliahering** [SokratisVidros/apicco#7]
The schema can include methods which define the relationship that multiple keys of the joi object should have.

eg.
https://github.com/hapijs/joi/blob/v15.0.0/API.md#objectorpeers
```
const schema = Joi.object().keys({
    a: Joi.any(),
    b: Joi.any()
}).or('a', 'b');
```

This expression is not supported by apicco and such schema cannot get validated.

**Comment by klouvas** [comment]
https://github.com/SokratisVidros/apicco/pull/19

**Comment by klouvas** [comment]
Should i open a PR with an update in the README example to showcase this and a minor version bump?
cc: @SokratisVidros

**Comment by SokratisVidros** [comment]
I've bumped the version already

**Comment by klouvas** [comment]
my bad :(
i've updated the README:
https://github.com/SokratisVidros/apicco/pull/23
